version: '3.5'
services:
    com-6ix-auth0-user-prov:
        container_name: com-6ix-auth0-user-prov
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8080:8080"
        restart: always
        image: malotian/com-6ix-auth0-user-prov:latest

networks:
    docker.local:
       driver: bridge
       name: docker.local
       